In [95]:
import pandas as pd

In [96]:
# leemos los csvs
df1 = pd.read_csv('datos_tabla1.csv')
df2 = pd.read_csv('datos_tabla2.csv')
df3 = pd.read_csv('datos_tabla3.csv')

In [97]:
# es necesario para unir, una columna año
# sacar el año del nombre del pdf
df1['anio'] = df1['pdf_name'].str.extract(r'(\d{4})').astype(int)
df2['anio'] = df2['pdf_name'].str.extract(r'(\d{4})').astype(int)
df3['anio'] = df3['pdf_name'].str.extract(r'(\d{4})').astype(int)

In [98]:
# creamos la columna fecha
df1['fecha'] = pd.to_datetime(
    dict(year=df1['anio'], month=df1['mes_num'], day=df1['dia'])
)

df2['fecha'] = pd.to_datetime(
    dict(year=df2['anio'], month=df2['mes_num'], day=df2['dia'])
)

df3['fecha'] = pd.to_datetime(
    dict(year=df3['anio'], month=df3['mes_num'], day=df3['dia'])
)

In [99]:
# e nu mismo pdf hay varios días por lo que no es un ID
df1 = df1.drop(columns=['pdf_name'])
df2 = df2.drop(columns=['pdf_name'])
df3 = df3.drop(columns=['pdf_name'])

# borramos los duplicados

In [101]:
df1 = df1.drop_duplicates()
df2 = df2.drop_duplicates()
df3 = df3.drop_duplicates()

In [107]:
# vemos que aún hay duplicados por fehcas
duplicado1 = df1[df1.duplicated(subset=['fecha'], keep=False)].sort_values('fecha')
duplicado1

      mes  mes_num  dia  mayorista  minorista  anio      fecha
1581  sep        9   21       5.38       6.56  2024 2024-09-21
1591  sep        9   21       4.88       5.30  2024 2024-09-21
1592  sep        9   28       4.60       5.10  2024 2024-09-28
1588  sep        9   28       5.18       6.40  2024 2024-09-28
268   sep        9    7       4.90       5.40  2025 2025-09-07
...   ...      ...  ...        ...        ...   ...        ...
621   abr        4   18       6.39       6.48  2026 2026-04-18
622   abr        4   19       5.61       6.48  2026 2026-04-19
610   abr        4   19       6.23       7.43  2026 2026-04-19
735   abr        4   20       6.15       7.44  2026 2026-04-20
747   abr        4   20       6.01       5.80  2026 2026-04-20

[266 rows x 7 columns]

142

In [62]:
df1

                 pdf_name  mes  mes_num  dia  mayorista  minorista  anio
0       09_abril_2026.pdf  mar        3   27       6.25       7.53  2026
1       09_abril_2026.pdf  mar        3   28       6.25       7.53  2026
2       09_abril_2026.pdf  mar        3   29       6.25       7.53  2026
3       09_abril_2026.pdf  mar        3   30       6.18       7.45  2026
4       09_abril_2026.pdf  mar        3   31       6.05       7.45  2026
...                   ...  ...      ...  ...        ...        ...   ...
1645  31_octubre_2025.pdf  oct       10   28       4.73       6.06  2025
1646  31_octubre_2025.pdf  oct       10   29       4.80       6.02  2025
1647  31_octubre_2025.pdf  oct       10   30       4.80       6.02  2025
1648  31_octubre_2025.pdf  oct       10   19       3.95       4.45  2025
1649  31_octubre_2025.pdf  oct       10   26       4.30       4.55  2025

[1650 rows x 7 columns]

In [ ]:
# borrar duplicados del df1, o sea que todo este duplciado

In [64]:
df1.duplicated(subset=['mes_num', 'dia', 'anio']).sum()

1419

In [66]:
#borramos los duplciados del df1
df1 = df1.drop_duplicates(subset=['anio', 'mes_num', 'dia'])

In [68]:
df1.duplicated(subset=['anio', 'mes_num', 'dia']).sum()

0

# borramos los duplicados del df2

In [69]:
df2

,mes,mes_num,dia,oferta_lima,oferta_sierra,oferta_costa_norte,oferta_selva,oferta_costa_sur,oferta_total,anio
0,mar,3,27,156113.0,79156.0,16041.0,8718.0,0.0,260028.0,2026
1,mar,3,28,100245.0,103792.0,7442.0,3626.0,0.0,215105.0,2026
2,mar,3,29,35028.0,34428.0,0.0,0.0,0.0,69456.0,2026
3,mar,3,30,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,2026
4,mar,3,31,41856.0,41125.0,0.0,4700.0,0.0,87681.0,2026
...,...,...,...,...,...,...,...,...,...,...
2263,oct,10,27,136600.0,123066.0,53975.0,8864.0,0.0,322505.0,2025
2264,oct,10,28,143049.0,41950.0,15659.0,2858.0,0.0,203516.0,2025
2265,oct,10,29,132777.0,110764.0,16146.0,17205.0,0.0,276892.0,2025
2266,oct,10,30,127747.0,80565.0,33882.0,13164.0,0.0,255357.0,2025
2267,oct,10,31,NaN,NaN,NaN,NaN,NaN,NaN,2025

In [70]:
df2.duplicated(subset=['anio', 'mes_num', 'dia']).sum()

2040

In [50]:
#borramos los duplicados
df2 = df2.drop_duplicates(subset=['pdf_name', 'mes_num', 'dia'])

C:\Users\JHOSSEP\AppData\Local\Temp\ipykernel_17592\445819772.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['anio'] = df1['pdf_name'].str.extract(r'(\d{4})').astype(int)
C:\Users\JHOSSEP\AppData\Local\Temp\ipykernel_17592\445819772.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['anio'] = df2['pdf_name'].str.extract(r'(\d{4})').astype(int)

# Borramos los duplciados del df3

In [58]:
df3.duplicated(subset=['pdf_name', 'mes_num', 'dia']).sum()

603

# Borramos los duplicados por llaves

In [54]:
df1

                 pdf_name  mes  mes_num  dia  mayorista  minorista  anio
0       09_abril_2026.pdf  mar        3   27       6.25       7.53  2026
1       09_abril_2026.pdf  mar        3   28       6.25       7.53  2026
2       09_abril_2026.pdf  mar        3   29       6.25       7.53  2026
3       09_abril_2026.pdf  mar        3   30       6.18       7.45  2026
4       09_abril_2026.pdf  mar        3   31       6.05       7.45  2026
...                   ...  ...      ...  ...        ...        ...   ...
1643  31_octubre_2025.pdf  oct       10   26       4.73       5.87  2025
1644  31_octubre_2025.pdf  oct       10   27       4.73       6.06  2025
1645  31_octubre_2025.pdf  oct       10   28       4.73       6.06  2025
1646  31_octubre_2025.pdf  oct       10   29       4.80       6.02  2025
1647  31_octubre_2025.pdf  oct       10   30       4.80       6.02  2025

[1203 rows x 7 columns]

In [55]:
print("df1")
print(df1.groupby(["anio", "mes_num", "dia"]).size().sort_values(ascending=False))

# vemos que hay duplicados por llave

df1
anio  mes_num  dia
2025  10       18     11
               19     11
2026  4        6      11
               8      11
2025  11       15     10
                      ..
               29      1
      12       1       1
2024  9        17      1
2025  12       25      1
2024  9        14      1
Length: 231, dtype: int64

In [57]:
# veamos los datos del 16 de septiembre
df1[(df1['mes_num'] == 9) & (df1['dia'] == 16)]

                   pdf_name  mes  mes_num  dia  mayorista  minorista  anio
376   17_setiembre_2025.pdf  sep        9   16       5.28       6.52  2025
476   18_setiembre_2025.pdf  sep        9   16       5.28       6.52  2025
591   19_setiembre_2025.pdf  sep        9   16       5.28       6.52  2025
955   23_setiembre_2025.pdf  sep        9   16       5.28       6.52  2025
1050  24_setiembre_2025.pdf  sep        9   16       5.28       6.52  2025
1166  25_setiembre_2025.pdf  sep        9   16       5.28       6.52  2025
1283  26_setiembre_2025.pdf  sep        9   16       5.28       6.52  2025
1483  29_setiembre_2025.pdf  sep        9   16       5.28       6.52  2025

In [52]:
df1

                 pdf_name  mes  mes_num  dia  mayorista  minorista  anio
0       09_abril_2026.pdf  mar        3   27       6.25       7.53  2026
1       09_abril_2026.pdf  mar        3   28       6.25       7.53  2026
2       09_abril_2026.pdf  mar        3   29       6.25       7.53  2026
3       09_abril_2026.pdf  mar        3   30       6.18       7.45  2026
4       09_abril_2026.pdf  mar        3   31       6.05       7.45  2026
...                   ...  ...      ...  ...        ...        ...   ...
1643  31_octubre_2025.pdf  oct       10   26       4.73       5.87  2025
1644  31_octubre_2025.pdf  oct       10   27       4.73       6.06  2025
1645  31_octubre_2025.pdf  oct       10   28       4.73       6.06  2025
1646  31_octubre_2025.pdf  oct       10   29       4.80       6.02  2025
1647  31_octubre_2025.pdf  oct       10   30       4.80       6.02  2025

[1203 rows x 7 columns]

In [13]:
df2

,pdf_name,mes,mes_num,dia,oferta_lima,oferta_sierra,oferta_costa_norte,oferta_selva,oferta_costa_sur,oferta_total,anio
0,09_abril_2026.pdf,mar,3,27,156113.0,79156.0,16041.0,8718.0,0.0,260028.0,2026
1,09_abril_2026.pdf,mar,3,28,100245.0,103792.0,7442.0,3626.0,0.0,215105.0,2026
2,09_abril_2026.pdf,mar,3,29,35028.0,34428.0,0.0,0.0,0.0,69456.0,2026
3,09_abril_2026.pdf,mar,3,30,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,2026
4,09_abril_2026.pdf,mar,3,31,41856.0,41125.0,0.0,4700.0,0.0,87681.0,2026
...,...,...,...,...,...,...,...,...,...,...,...
1129,31_octubre_2025.pdf,oct,10,27,136600.0,123066.0,53975.0,8864.0,0.0,322505.0,2025
1130,31_octubre_2025.pdf,oct,10,28,143049.0,41950.0,15659.0,2858.0,0.0,203516.0,2025
1131,31_octubre_2025.pdf,oct,10,29,132777.0,110764.0,16146.0,17205.0,0.0,276892.0,2025
1132,31_octubre_2025.pdf,oct,10,30,127747.0,80565.0,33882.0,13164.0,0.0,255357.0,2025
1133,31_octubre_2025.pdf,oct,10,31,NaN,NaN,NaN,NaN,NaN,NaN,2025

# Merge df1 y df2

In [14]:
# debemos crear una sola base para las 3 tablas, el ID será pdf_name
# merge de df1, df2  por pdf name
df_1_2 = df1.merge(df2, on=['dia', 'mes_num', 'anio'], how='inner')

In [15]:
df_1_2

,pdf_name_x,mes_x,mes_num,dia,mayorista,minorista,anio,pdf_name_y,mes_y,oferta_lima,oferta_sierra,oferta_costa_norte,oferta_selva,oferta_costa_sur,oferta_total
0,09_abril_2026.pdf,mar,3,27,6.25,7.53,2026,09_abril_2026.pdf,mar,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
1,09_abril_2026.pdf,mar,3,27,6.25,7.53,2026,30_marzo_2026.pdf,mar,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
2,09_abril_2026.pdf,mar,3,27,6.25,7.53,2026,31_marzo_2026.pdf,mar,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
3,10_abril_2026.pdf,mar,3,27,5.92,6.00,2026,09_abril_2026.pdf,mar,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
4,10_abril_2026.pdf,mar,3,27,5.92,6.00,2026,30_marzo_2026.pdf,mar,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7449,30_setiembre_2024.pdf,sep,9,25,5.18,6.50,2024,30_setiembre_2024.pdf,sep,109098.0,61000.0,29172.0,5295.0,0.0,204565.0
7450,30_setiembre_2024.pdf,sep,9,26,5.18,6.40,2024,30_setiembre_2024.pdf,sep,114690.0,68789.0,15954.0,2348.0,0.0,201781.0
7451,30_setiembre_2024.pdf,sep,9,27,5.18,6.40,2024,30_setiembre_2024.pdf,sep,128751.0,75732.0,5981.0,4151.0,0.0,214614.0
7452,30_setiembre_2024.pdf,sep,9,28,5.18,6.40,2024,30_setiembre_2024.pdf,sep,23548.0,23030.0,0.0,0.0,0.0,46578.0
7453,30_setiembre_2024.pdf,sep,9,29,5.13,6.44,2024,30_setiembre_2024.pdf,sep,143966.0,106549.0,51092.0,11123.0,0.0,312730.0

In [16]:
# verificamos duplicados
df1.duplicated(subset=['pdf_name', 'mes_num', 'dia']).sum()

0

In [17]:
#revisamos si mes x y mes si hay datos que difieren
df_diff = df_1_2[df_1_2['mes_x'] != df_1_2['mes_y']]
df_diff.head()

Empty DataFrame
Columns: [pdf_name_x, mes_x, mes_num, dia, mayorista, minorista, anio, pdf_name_y, mes_y, oferta_lima, oferta_sierra, oferta_costa_norte, oferta_selva, oferta_costa_sur, oferta_total]
Index: []

In [18]:
# no hay datos que diferean entonces ya podemos borrar mes_y
df_1_2.drop(columns=['mes_y'], inplace=True)
# rename as mes
df_1_2.rename(columns={'mes_x': 'mes'}, inplace=True)

In [19]:
df_1_2

,pdf_name_x,mes,mes_num,dia,mayorista,minorista,anio,pdf_name_y,oferta_lima,oferta_sierra,oferta_costa_norte,oferta_selva,oferta_costa_sur,oferta_total
0,09_abril_2026.pdf,mar,3,27,6.25,7.53,2026,09_abril_2026.pdf,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
1,09_abril_2026.pdf,mar,3,27,6.25,7.53,2026,30_marzo_2026.pdf,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
2,09_abril_2026.pdf,mar,3,27,6.25,7.53,2026,31_marzo_2026.pdf,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
3,10_abril_2026.pdf,mar,3,27,5.92,6.00,2026,09_abril_2026.pdf,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
4,10_abril_2026.pdf,mar,3,27,5.92,6.00,2026,30_marzo_2026.pdf,156113.0,79156.0,16041.0,8718.0,0.0,260028.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7449,30_setiembre_2024.pdf,sep,9,25,5.18,6.50,2024,30_setiembre_2024.pdf,109098.0,61000.0,29172.0,5295.0,0.0,204565.0
7450,30_setiembre_2024.pdf,sep,9,26,5.18,6.40,2024,30_setiembre_2024.pdf,114690.0,68789.0,15954.0,2348.0,0.0,201781.0
7451,30_setiembre_2024.pdf,sep,9,27,5.18,6.40,2024,30_setiembre_2024.pdf,128751.0,75732.0,5981.0,4151.0,0.0,214614.0
7452,30_setiembre_2024.pdf,sep,9,28,5.18,6.40,2024,30_setiembre_2024.pdf,23548.0,23030.0,0.0,0.0,0.0,46578.0
7453,30_setiembre_2024.pdf,sep,9,29,5.13,6.44,2024,30_setiembre_2024.pdf,143966.0,106549.0,51092.0,11123.0,0.0,312730.0

# Merge df1_2 + df3

In [20]:
df1

                 pdf_name  mes  mes_num  dia  mayorista  minorista  anio
0       09_abril_2026.pdf  mar        3   27       6.25       7.53  2026
1       09_abril_2026.pdf  mar        3   28       6.25       7.53  2026
2       09_abril_2026.pdf  mar        3   29       6.25       7.53  2026
3       09_abril_2026.pdf  mar        3   30       6.18       7.45  2026
4       09_abril_2026.pdf  mar        3   31       6.05       7.45  2026
...                   ...  ...      ...  ...        ...        ...   ...
1643  31_octubre_2025.pdf  oct       10   26       4.73       5.87  2025
1644  31_octubre_2025.pdf  oct       10   27       4.73       6.06  2025
1645  31_octubre_2025.pdf  oct       10   28       4.73       6.06  2025
1646  31_octubre_2025.pdf  oct       10   29       4.80       6.02  2025
1647  31_octubre_2025.pdf  oct       10   30       4.80       6.02  2025

[1203 rows x 7 columns]

In [21]:
df_1_2_3 = df_1_2.merge(df3, on=['dia', 'mes_num', 'anio'], how='inner')

In [22]:
df_1_2_3

,pdf_name_x,mes_x,mes_num,dia,mayorista,minorista,anio,pdf_name_y,oferta_lima,oferta_sierra,oferta_costa_norte,oferta_selva,oferta_costa_sur,oferta_total,pdf_name,mes_y,precio_ica,precio_libertad,precio_lima
0,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,09_abril_2026.pdf,mar,5.88,4.88,5.97
1,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,10_abril_2026.pdf,mar,5.88,4.88,5.97
2,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,13_abril_2026.pdf,mar,5.88,4.88,5.97
3,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,14_abril_2026.pdf,mar,5.88,4.88,5.97
4,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,15_abril_2026.pdf,mar,5.88,4.88,5.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51603,30_setiembre_2024.pdf,sep,9,26,5.18,6.40,2024,30_setiembre_2024.pdf,114690.0,68789.0,15954.0,2348.0,0.0,201781.0,30_setiembre_2024.pdf,sep,4.96,4.50,5.30
51604,30_setiembre_2024.pdf,sep,9,27,5.18,6.40,2024,30_setiembre_2024.pdf,128751.0,75732.0,5981.0,4151.0,0.0,214614.0,30_setiembre_2024.pdf,sep,5.21,4.40,5.10
51605,30_setiembre_2024.pdf,sep,9,27,5.18,6.40,2024,30_setiembre_2024.pdf,128751.0,75732.0,5981.0,4151.0,0.0,214614.0,30_setiembre_2024.pdf,sep,5.21,4.40,5.10
51606,30_setiembre_2024.pdf,sep,9,29,5.13,6.44,2024,30_setiembre_2024.pdf,143966.0,106549.0,51092.0,11123.0,0.0,312730.0,30_setiembre_2024.pdf,sep,4.90,4.40,5.10
51607,30_setiembre_2024.pdf,sep,9,29,5.13,6.44,2024,30_setiembre_2024.pdf,143966.0,106549.0,51092.0,11123.0,0.0,312730.0,30_setiembre_2024.pdf,sep,4.90,4.40,5.10

In [23]:
# revisamos si mes_x y mes_y hay datos que difieren
#revisamos si mes x y mes si hay datos que difieren
df_diff = df_1_2_3[df_1_2_3['mes_x'] != df_1_2_3['mes_y']]
df_diff.head()

# No hay datos que difieren entonces ya podemos borrar mes_y
df_1_2_3.drop(columns=['mes_y'], inplace=True)
df_1_2_3.rename(columns={'mes_x': 'mes'}, inplace=True)

# Data final

In [24]:
df_1_2_3

,pdf_name_x,mes,mes_num,dia,mayorista,minorista,anio,pdf_name_y,oferta_lima,oferta_sierra,oferta_costa_norte,oferta_selva,oferta_costa_sur,oferta_total,pdf_name,precio_ica,precio_libertad,precio_lima
0,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,09_abril_2026.pdf,5.88,4.88,5.97
1,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,10_abril_2026.pdf,5.88,4.88,5.97
2,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,13_abril_2026.pdf,5.88,4.88,5.97
3,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,14_abril_2026.pdf,5.88,4.88,5.97
4,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,15_abril_2026.pdf,5.88,4.88,5.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51603,30_setiembre_2024.pdf,sep,9,26,5.18,6.40,2024,30_setiembre_2024.pdf,114690.0,68789.0,15954.0,2348.0,0.0,201781.0,30_setiembre_2024.pdf,4.96,4.50,5.30
51604,30_setiembre_2024.pdf,sep,9,27,5.18,6.40,2024,30_setiembre_2024.pdf,128751.0,75732.0,5981.0,4151.0,0.0,214614.0,30_setiembre_2024.pdf,5.21,4.40,5.10
51605,30_setiembre_2024.pdf,sep,9,27,5.18,6.40,2024,30_setiembre_2024.pdf,128751.0,75732.0,5981.0,4151.0,0.0,214614.0,30_setiembre_2024.pdf,5.21,4.40,5.10
51606,30_setiembre_2024.pdf,sep,9,29,5.13,6.44,2024,30_setiembre_2024.pdf,143966.0,106549.0,51092.0,11123.0,0.0,312730.0,30_setiembre_2024.pdf,4.90,4.40,5.10
51607,30_setiembre_2024.pdf,sep,9,29,5.13,6.44,2024,30_setiembre_2024.pdf,143966.0,106549.0,51092.0,11123.0,0.0,312730.0,30_setiembre_2024.pdf,4.90,4.40,5.10

In [25]:
# revismos nulos
df_1_2_3.isnull().sum()

pdf_name_x               0
mes                      0
mes_num                  0
dia                      0
mayorista                0
minorista                0
anio                     0
pdf_name_y               0
oferta_lima           1962
oferta_sierra         1962
oferta_costa_norte    1962
oferta_selva          1962
oferta_costa_sur      1962
oferta_total          1962
pdf_name                 0
precio_ica               0
precio_libertad          0
precio_lima              0
dtype: int64

In [26]:
df_1_2_3.shape

(51608, 18)

## Agregar variable fecha

In [27]:
df_fechas = df_1_2_3.copy()

# Crear variable fecha
df_fechas["fecha"] = pd.to_datetime(
    dict(
        year=df_fechas["anio"],
        month=df_fechas["mes_num"],
        day=df_fechas["dia"]
    )
)

In [28]:
df_fechas

,pdf_name_x,mes,mes_num,dia,mayorista,minorista,anio,pdf_name_y,oferta_lima,oferta_sierra,oferta_costa_norte,oferta_selva,oferta_costa_sur,oferta_total,pdf_name,precio_ica,precio_libertad,precio_lima,fecha
0,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,09_abril_2026.pdf,5.88,4.88,5.97,2026-03-30
1,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,10_abril_2026.pdf,5.88,4.88,5.97,2026-03-30
2,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,13_abril_2026.pdf,5.88,4.88,5.97,2026-03-30
3,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,14_abril_2026.pdf,5.88,4.88,5.97,2026-03-30
4,09_abril_2026.pdf,mar,3,30,6.18,7.45,2026,09_abril_2026.pdf,198524.0,115340.0,48429.0,21317.0,0.0,383610.0,15_abril_2026.pdf,5.88,4.88,5.97,2026-03-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51603,30_setiembre_2024.pdf,sep,9,26,5.18,6.40,2024,30_setiembre_2024.pdf,114690.0,68789.0,15954.0,2348.0,0.0,201781.0,30_setiembre_2024.pdf,4.96,4.50,5.30,2024-09-26
51604,30_setiembre_2024.pdf,sep,9,27,5.18,6.40,2024,30_setiembre_2024.pdf,128751.0,75732.0,5981.0,4151.0,0.0,214614.0,30_setiembre_2024.pdf,5.21,4.40,5.10,2024-09-27
51605,30_setiembre_2024.pdf,sep,9,27,5.18,6.40,2024,30_setiembre_2024.pdf,128751.0,75732.0,5981.0,4151.0,0.0,214614.0,30_setiembre_2024.pdf,5.21,4.40,5.10,2024-09-27
51606,30_setiembre_2024.pdf,sep,9,29,5.13,6.44,2024,30_setiembre_2024.pdf,143966.0,106549.0,51092.0,11123.0,0.0,312730.0,30_setiembre_2024.pdf,4.90,4.40,5.10,2024-09-29
51607,30_setiembre_2024.pdf,sep,9,29,5.13,6.44,2024,30_setiembre_2024.pdf,143966.0,106549.0,51092.0,11123.0,0.0,312730.0,30_setiembre_2024.pdf,4.90,4.40,5.10,2024-09-29

In [29]:
# Revisar si hubo fechas inválidas
print("Fechas inválidas:", df_fechas["fecha"].isna().sum())

Fechas inválidas: 0

In [31]:
df_fechas.duplicated(subset=['fecha']).sum()

51501

In [33]:
df_fechas.shape

(51608, 19)

In [36]:
# cantidad de fechas duplicadas por fecha
df_fechas['fecha'].value_counts().head(10)

fecha
2025-10-18    2662
2025-10-20    2200
2025-11-15    1800
2025-10-17    1782
2026-03-17    1620
2025-10-21    1620
2025-11-17    1620
2026-04-10    1458
2025-11-14    1458
2026-03-18    1458
Name: count, dtype: int64

In [35]:
# Rango completo diario
fecha_min = df_fechas["fecha"].min()
fecha_max = df_fechas["fecha"].max()

rango_completo = pd.DataFrame({
    "fecha": pd.date_range(start=fecha_min, end=fecha_max, freq="D")
})

rango_completo

         fecha
0   2024-09-17
1   2024-09-18
2   2024-09-19
3   2024-09-20
4   2024-09-21
..         ...
577 2026-04-17
578 2026-04-18
579 2026-04-19
580 2026-04-20
581 2026-04-21

[582 rows x 1 columns]